# mnist-digital-numbers-of-caicloud
才云科技的书：《实战谷歌深度学习框架》第五章5.5例子，Python2.7，TF ==1.4可以正确运行;Python 3.5， 3.7都会报错：UnboundLocalError: local variable 'self' referenced before assignment
